# Generated by Django 3.2.18 on 2023-04-12 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('rok_wydania', models.IntegerField()),
                ('dostepnosc', models.BooleanField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.autor')),
            ],
        ),
    ]
